name: RPKitCMD
author: David2020xD
api: [3.0.0-ALPHA9]
load: STARTUP
version: 1.0
main: TEST\TEST

command:
	wizard:
		description: get a wand
		usage: /wizard
		
permissions:
	wizard:
		default: true
